language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
env:
  global:
  - secure: Ks2nS6aPY3iEuyPND6+n7hYATv3Uyhb884VbgxaEestxfgujdh6Cw/IOako0Zfv7qLXDOoacrLz1vf4LU38JqL/cYIielJ878nG3AOkz+UIz8cpUwT4Ea7ZpU8ftkAvGuvQ6kszdwcRBY7RMxdB2oxqtcMB31biBXuOwwkyTglY=
  - secure: XQTc3sJEKG2T1vwVIqF1jV/s2NacWN8BIB8/FC3efbrXH7klvA49iopiUz9sz1pkBOPeCpY2kUZONWZ4t1puyrwol7ghV7QOdaO3WnTLELKSUQ2J6H2D/LQHom/NZc9vWQ30k4Vdo3qOh46cpKa992Yj2fwB6N57Ra4zWI5h0yo=
